<?php

use Illuminate\Support\Facades\Route;
use Dedoc\Scramble\Scramble;

/*
|--------------------------------------------------------------------------
| Scramble Documentation Routes
|--------------------------------------------------------------------------
|
| These routes are used to serve the API documentation generated by Scramble.
| The documentation will be available at /docs/api
|
*/

// Register Scramble routes
Scramble::routes(function ($routes) {
    $routes->middleware(['web']);
});
